version: '3.8'

services:
  precision-digitizer:
    image: precision-digitizer
    build:
      context: ./precision-digitizer
    networks:
      - app-network
    volumes:
      - ./notebooks/dicoms:/datain
      - ./precision-viewer/src/assets:/dataout
    environment:
      - DATAIN=/datain
      - DATAOUT=/dataout

  precision-api:
    image: precision-api
    build:
      context: ./precision-api
    ports:
      - "3000:3000"
    networks:
      - app-network

  precision-viewer:
    image: precision-viewer
    build:
      context: ./precision-viewer
    ports:
      - "5000:5000"
    depends_on:
      - precision-api
    networks:
      - app-network
    environment:
      - API_HOST=http://precision-api:3000
    volumes:
      - ./precision-viewer:/dataout

networks:
  app-network:
    driver: bridge